name: Build Linux static binary distribution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Cache sources for third party dependencies
      uses: actions/cache@v1
      env:
        cache-name: cache-third-parties-sources
      with:
        path: derived/3rdparty
        key:  ${{ runner.os }}-sources-x86_64-linux-opt-3rd
        restore-keys: ${{ runner.os }}-sources-x86_64-linux-opt-3rd
    - name: Cache third party dependencies
      uses: actions/cache@v1
      env:
        cache-name: cache-third-parties
      with:
        path: derived/x86_64-linux-opt-3rd/3rdparty
        key:  ${{ runner.os }}-built-x86_64-linux-opt-3rd
        restore-keys: ${{ runner.os }}-built-x86_64-linux-opt-3rd 
    - name: Install prerequisites
      run: sudo apt-get install libgl1-mesa-dev
    - name: Make
      run: make staticbindist

