name: Build Linux Distributable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Fetch entire repository
      run: git fetch --prune --unshallow
    - name: Install prerequisites
      run: sudo apt-get install libgl1-mesa-dev
    - name: Make
      run: make staticbindist OPENMSX_TARGET_CPU=x86_64
    - name: Determine version
      id: get_version
      run: |
        OPENMSX_VERSION=`python3 build/version.py`
        echo ::set-output name=OPENMSX_VERSION::$OPENMSX_VERSION
    - name: Prepare redistributable directory
      run: |
        cd derived/x86_64-linux-opt-3rd/bindist
        mv install openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-x86_64-linux-opt-3rd
    - name: Upload redistributable zip
      uses: actions/upload-artifact@v1
      with:
        name: openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-x86_64-linux-opt-3rd.zip
        path: derived/x86_64-linux-opt-3rd/bindist/openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-x86_64-linux-opt-3rd
