name: Build macOS aarch64 Distributable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  target_cpu: aarch64
  target_os: darwin

jobs:
  build:

    runs-on: macos-11.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Fetch entire repository
      run: git fetch --prune --unshallow
    - name: Make
      run: make staticbindist OPENMSX_TARGET_CPU=$target_cpu
    - name: Determine version
      id: get_version
      run: |
        OPENMSX_VERSION=`python3 build/version.py`
        echo ::set-output name=OPENMSX_VERSION::$OPENMSX_VERSION
    - name: Rename redistributable dmg
      run: |
        cd derived/$target_cpu-$target_os-opt-3rd/bindist
        mv openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-mac-$target_cpu-bin.dmg openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-$target_cpu-$target_os-opt-3rd.dmg
    - name: Upload redistributable dmg
      uses: actions/upload-artifact@v1
      with:
        name: openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-$target_cpu-$target_os-opt-3rd.dmg
        path: derived/$target_cpu-$target_os-opt-3rd/openmsx-${{ steps.get_version.outputs.OPENMSX_VERSION }}-$target_cpu-$target_os-opt-3rd.dmg
